# Site settings
title: SudoPlay Games
email: joise@sudoplaygames.com
description: "SudoPlay Games is a small, independent game studio located in Oregon, USA."
baseurl: ""
url: "http://www.sudoplaygames.com"
twitter_username: sudoplaygames
github_username:  sudoplaygames

# Build settings
permalink: /blog/:year/:month/:day/:title.html

joise_version: "1.1.0"